import type { ReactNode } from "react";
import { useAuth } from "../../hooks/useAuth";
import { Link, useLocation } from "react-router-dom";

const tabs = [
  { name: "DASHBOARD", path: "/dashboard" },
  { name: "ANALYTICS", path: "/analytics" },
  { name: "USER MANAGEMENT", path: "/users" },
  { name: "TARGETS", path: "/targets" },
];

export function AppShell({
  children,
}: {
  children: ReactNode;
  activeTab?: string;
}) {
  const { logout } = useAuth();
  const location = useLocation();

  return (
    <div className="min-h-screen bg-white font-sans text-[#1a1c1e]">
      {/* Official Header */}
      <header className="mx-auto w-full max-w-[1400px] border-x border-t border-black px-8 py-6">
        <div className="flex items-end justify-between">
          <div className="flex items-center gap-2 text-4xl font-black tracking-tighter">
            <span className="text-[#e11d48]">C</span>
            <span>3MR</span>
          </div>
          <div className="text-[10px] font-black uppercase tracking-[0.2em] text-[#1a1c1e]">
            Official Management Portal
          </div>
        </div>
      </header>

      {/* Navigation */}
      <nav className="mx-auto w-full max-w-[1400px] border-x border-y border-black">
        <div className="flex px-4">
          {tabs.map((tab) => {
            const isActive = location.pathname === tab.path;
            return (
              <Link
                key={tab.path}
                to={tab.path}
                className={`relative px-6 py-5 text-[11px] font-black tracking-widest transition hover:text-[#e11d48] ${
                  isActive ? "text-[#1a1c1e]" : "text-[#5e6671]"
                }`}
              >
                {tab.name}
                {isActive && (
                  <div className="absolute bottom-[-1px] left-0 h-[3px] w-full bg-[#e11d48]" />
                )}
              </Link>
            );
          })}
          <div className="ml-auto flex items-center px-4">
            <button
              onClick={logout}
              className="text-[10px] font-black uppercase tracking-widest text-red-600 hover:underline"
            >
              Logout
            </button>
          </div>
        </div>
      </nav>

      <main className="mx-auto w-full max-w-[1400px] border-x border-b border-black p-8">
        {children}
        
        <footer className="mt-20 border-t border-slate-100 pt-8 text-[10px] font-medium text-slate-400 italic">
          Generated by C3MR System - Confidential Document
        </footer>
      </main>
    </div>
  );
}
