@startsalt
{+
  { <b>< C3MR Field App </b> }
  ===
  <b>Task: Siti Aminah
  Payment Status:
  ^Promise to Pay^
  Notes:
  {S
  Will pay tomorrow.
  .
  }
  [ Upload Photo Evidence ]
  [    Submit Report    ]
}
@endsalt
